#!/usr/bin/env bash
# display the records and address

check_domain() {
	subd=("www" "lb-01" "web-01" "web-02")
	for i in "${subd[@]}";
	do
		dig "${i}.$1" | grep -A1 'ANSWER SECTION'| \
		awk 'FNR == 2 {printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$i"
	done
	}

check_subdomain() {
	dig "${2}"."$1" | grep -A1 'ANSWER SECTION:' | \
	awk 'FNR == 2 {printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$2"
}

if [ $# -lt 1 ]
then
	echo "*** Provide domain name ***"
elif [ $# -eq 1 ]
then
	check_domain "$1";
else
	check_subdomain "$1" "$2";
fi
