#!/usr/bin/env bash
# transfers file from client to
# a server using scp

if [ "$#" -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -lt 4 ]
then
	scp -o StrictHostKeyChecking=no -i "$1" "$3@$2":~/
else
	scp -o "$4"  StrictKeyChecking=no -i "$1" "$3@$2":~/
fi
