#!/usr/bin/env bash
# installs and configures nginx on ubuntu

sudo su
apt-get update
apt-get install nginx -y
ufw allow "Nginx HTTP"
echo "Hello World!" > /var/www/html/index.html
service nginx start
