#!/usr/bin/env bash
# installs and configures nginx on ubuntu

sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow "Nginx HTTP"
sudo chmod -R a+rw /var/www
sudo touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
printf %s "server {
	listen 80;
	listen [::]:80 default_server;
	root /etc/nginx/html
	index index.html index.htm
	location /redirect_me {
		return 301  https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}" > /etc/nginx/sites-available/default
sudo service nginx start
