#!/usr/bin/env bash
# Install and confiigure haproxy load balancer

loadbalancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 101550-web-01 34.201.174.223:80 check
    server 101550-web-02 54.237.49.116:80 check
"
# Update packages
apt-get -y update
apt-get -y upgrade

# Add HAProxy PPA
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update


# Install HAProxy
apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$loadbalancer" >>  /etc/haproxy/haproxy.cfg
service haproxy restart
