#!/usr/bin/env bash
# Install and confiigure haproxy load balancer

loadbalancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 101550-web-01 34.232.78.21:80 check
    server 101550-web-02 54.237.49.116:80 check
"
# Update packages
sudo apt-get -y update
sudo apt-get -y upgrade

# Add HAProxy PPA
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update


# Install HAProxy
sudo apt-get -y install haproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$loadbalancer" >>  /etc/haproxy/haproxy.cfg
sudo service haproxy restart
