#!/usr/bin/env bash
#create file, display sent, trap kill
#delete fil

term(){
	rm /var/run/myscript.pid
	exit
}

echo $$ > /var/run/myscript.pid
i=0
while [ $i -lt 1 ]
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command"' SIGTERM
	trap 'echo "Y U no love me?!" && term' SIGINT
	trap 'term' SIGQUIT
done
