#!/usr/bin/env bash
# manages processe


if [ "$1" == "start" ]
then
	sudo ./manage_my_process start
	echo "$$" > /var/run/my_process.pid
	echo "manage_my_process started"
elif [ "$1" ==  "stop" ]
then
	sudo ./manage_my_process stop
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"
elif [ "$1" == "restart" ]
then
	sudo ./manage_my_process restart
	rm /var/run/my_process.pid
	echo "manage_my_process restarted"
	echo "$$" > /var/run/my_process.pid
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
