#!/usr/bin/env bash
# Displays time

hour=0
minutes=1
while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	while [ $minutes -le 59 ]
	do
		echo $minutes
		minutes=$((minutes+1))
	done
	hour=$((hour+1))
	minutes=$((1))
done
